apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volumes
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.3.0.3
    path: "/"
